name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Run linter and tests
        run: npx eslint . && npm run test
  build:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Initialize SSH agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add Host Key
        run: echo ${{secrets.HKEY}} >> ~/.ssh/known_hosts
      
      - name: Build
        run: ssh ${{ secrets.HOST }} meta-pixels build
  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Initialize SSH agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add Host Key
        run: echo ${{secrets.HKEY}} >> ~/.ssh/known_hosts
      
      - name: Deploy
        run: ssh ${{ secrets.HOST }} meta-pixels deploy
